## <span style="color:#50fa7b;">Ejercicio 1</span>
Llamamos matriz cero y se denota O, la cual contiene muchos ceros, comprobar las siguientes propiedades:
<br>a. $A+O = A-O = A$
<br>b. $A-A=0$

In [1]:
import numpy as np
""" 
Se declaran las matricdes ceros y 
la matriz A (la cual es una matriz arbitraria de la misma extención de la matriz ceros).
"""
A = np.array([[1,4],[-1,3],[2,-9]])
ceros=np.zeros((3,2))

"""
La comprobacion del inciso a se realiza de la siguiente manera:
1. Se comprueba que todos los elementos de la matriz resultante de comprobar si A+ceros=A,
dicha matriz debe contener solo Trues si la preposición es correcta. Dicha comprobacion se hace con la
función all de numpy.
2. Se realiza la misma comprobacion para A-ceros=A.
3. Finalmente se multiplican ambas salidas debido a que es una comprobación AND, ambas preposiciones deben
ser verdaderas para que se cumpla la propiedad.
"""
comprobacion = np.all((A+ceros==A) == True) * np.all((A-ceros==A) == True)
print("a.", "Se cumple la propiedad: A+O = A-O = A." if comprobacion else "No se cumple la propiedad: A+O = A-O = A.")

"""
La comprobacion del inciso b se realiza de la siguiente manera:
Se coprueba que en todas las pociciones de la matriz resultante de que comprar a la matriz A-A = O
sean True
"""
comprobacion = np.all(A-A==ceros)
print("b.", "Se cumple la propiedad A-A = 0." if comprobacion else "No se cumple la propiedad A-A = 0.")



a. Se cumple la propiedad: A+O = A-O = A.
b. Se cumple la propiedad A-A = 0.


## <span style="color:#50fa7b;">Ejercicio 2</span>
Sea:
<br>
$
A=
\begin{bmatrix}
    3 & 0 \\
    -1 & 5 
\end{bmatrix}
$
<br>
$
B=
\begin{bmatrix}
    4 & -2 & 1\\
    0 & 2 & 3
\end{bmatrix}
$
<br>
Realizar:
* $A+3B$
* $AB$
* $A³$
* $B²$
* $(5A)B$

In [2]:
#Definimos las metrices con ayuda de numpy
A = np.array([[3,0],[-1,5]])
B = np.array([[4,-2,1],[0,2,3]])

#Primer inciso A + 3B
"""
Como no se pueden sumar directamente dos matrices que no tengan las mismas dimencionaes
se agregara un 0 en los indices [0][2] y [0][2]. Para insertar los 0 se usa la función
inser de numpy, esto devuelve un arreglo de la forma [ 3  0  9 -1  5  9], por lo que 
lo unico que queda es organizarlo en una matriz de dimenciones (2,3), esto se logra con
la función reshape de numpy.
Finalmente se suman ambas matrices y se imprime por consola.
"""
A1= np.insert(A,(2,4),0)
A1 = A1.reshape(2,3)
print("1.A + 3B")
print(A1+(3*B))

#Segundo inciso AB
print("--------------------")
print("2. AB")
print(A@B)

#Tercer inciso A^3
print("--------------------")
print("3.A^3")
print(pow(A,3))

#Cuarto inciso A^2
print("--------------------")
print("4.B^2")
print(pow(B,2))

#Quinto inciso 5A(B)
print("--------------------")
print("5.(5A)B")
print((5*A)@B)

1.A + 3B
[[15 -6  3]
 [-1 11  9]]
--------------------
2. AB
[[12 -6  3]
 [-4 12 14]]
--------------------
3.A^3
[[ 27   0]
 [ -1 125]]
--------------------
4.B^2
[[16  4  1]
 [ 0  4  9]]
--------------------
5.(5A)B
[[ 60 -30  15]
 [-20  60  70]]


## <span style="color:#50fa7b;">Ejercicio 3</span>
Dos restaurantes desean comprar frutas para la siguiente semana. La tabla 1 muestra que tipo de fruta y en que cantidades la desean adquirir. Se tienen dos centros comerciales, la tabla 2 muestra sus precios. ¿Cuánto costara comprar las grutas para cada uno de los centros comerciales?
|                 | Naranjas | Manzanas | Piñas |
|-----------------|----------|----------|-------|
| Restaurante Uno | 30       | 15       | 4     |
| Restaurante Dos | 25       | 18       | 8     |

|                    | Naranjas | Manzanas | Piñas |
|--------------------|----------|----------|-------|
| Centro comercial 1 | 1.2      | 2.2      | 4.5   |
| Centro comercial 2 | 1.3      | 2.1      | 4.6   |


In [3]:
restaurantes = np.array([[30, 15, 4],[25, 18, 8]])
centrosComerciales = np.array([[1.2, 2.2, 4.5],[1.3, 2.1, 4.6]])
print("---------- Primer restaurante ----------")
print("Primer centro comercial: ", restaurantes[0]*centrosComerciales[0], " Total: ", sum(restaurantes[0]*centrosComerciales[0]))
print("Segundo centro comercial:", restaurantes[0]*centrosComerciales[1], " Total: ", sum(restaurantes[0]*centrosComerciales[1]))
print("Para el primer restaurante", "es mejor comprar en el primer centro comercial." if (sum(restaurantes[0]*centrosComerciales[0])<sum(restaurantes[0]*centrosComerciales[1])) else "es mejor comprar en el segundo centro comercial.")
print("---------- Segundo restaurante ----------")
print("Primer centro comercial: ", restaurantes[1]*centrosComerciales[0], " Total: ", sum(restaurantes[1]*centrosComerciales[0]))
print("Segundo centro comercial:", restaurantes[1]*centrosComerciales[1], " Total: ", sum(restaurantes[1]*centrosComerciales[1]))
print("Para el segundo restaurante", "es mejor comprar en el primer centro comercial." if (sum(restaurantes[1]*centrosComerciales[0])<sum(restaurantes[1]*centrosComerciales[1])) else "es mejor comprar en el segundo centro comercial.")

---------- Primer restaurante ----------
Primer centro comercial:  [36. 33. 18.]  Total:  87.0
Segundo centro comercial: [39.  31.5 18.4]  Total:  88.9
Para el primer restaurante es mejor comprar en el primer centro comercial.
---------- Segundo restaurante ----------
Primer centro comercial:  [30.  39.6 36. ]  Total:  105.6
Segundo centro comercial: [32.5 37.8 36.8]  Total:  107.10000000000001
Para el segundo restaurante es mejor comprar en el primer centro comercial.


## <span style="color:#50fa7b;">Ejercicio 4</span>
Una fabrica elabora tres productos (escobas, escobetas y cepillos) y los envía a dos almacenes para su cuidado. Elnúmero de unidades esta dado en la tabla 3.

|           | Escobas  | Escobetas| Cepillos |
|-----------|----------|----------|----------|
| Almacen 1 | 200      | 150      | 100      |
| Almacen 2 | 75       | 100      | 125      |

El costo de embarcar por camión es por cada cantidad de unidad de escob es 1.50, escobetas 1.0 y cepillos 2.0, el costo por tren es escoba 1.75, escobetas 1.50 y cepillos 1.0. Organizar la información en una matriz para ocupar la multiplicación de matrices, dependiendo de los resultados, indica que le conviene a la empresa embarcar con camión o tren.

|           | Escobas  | Escobetas| Cepillos |
|-----------|----------|----------|----------|
| Camión    | 1.5      | 1.0      | 2.0      |
| Tren      | 1.75     | 1.5      | 1.0      |

In [4]:
# Definimos las matrices de almacenes y transportes de manera tal que se elementosFilas = elementosColumnas
almacenes = np.array([[200, 150, 100] , [75 ,100 , 125]])
transportes = np.array([[1.5, 1.75] , [1.0, 1.5] , [2.0, 1.0]])

costos = np.matmul(almacenes, transportes)

print("Costos de transporte para el primer almacen:\n", "camión: ", costos[0,0], " | tren: ", costos[0,1])
print("Pra el primer almacén es mejor transportarlo por", "camión." if costos[0,0] < costos[0,1] else "tren.")
print("-------------------------------------------------------")
print("Costos de transporte para el segundo almacen:\n", "camión: ", costos[1,0], " | tren: ", costos[1,1])
print("Pra el segundo almacén es mejor transportarlo por", "camión." if costos[1,0] < costos[1,1] else "tren.")

Costos de transporte para el primer almacen:
 camión:  650.0  | tren:  675.0
Pra el primer almacén es mejor transportarlo por camión.
-------------------------------------------------------
Costos de transporte para el segundo almacen:
 camión:  462.5  | tren:  406.25
Pra el segundo almacén es mejor transportarlo por tren.


## <span style="color:#50fa7b;">Ejercicio 5</span>
Resolver los siguientes sistemas de ecuaciones:
* Sistema 1
<br>$3x+2y=6$
<br>$6x+4y=-9$
* Sistema 2
<br>$x+y=3$
<br>$x+4y=1$
* Sistema 3
<br>$2x-y+2z=3$
<br>$2x+3y-z=0$
<br>$x+2y+2z=-12$

In [5]:
# Función para resolver los sistemas
def solve(coeficientes, igualacion):
    try:
        resultado = np.linalg.solve(coeficientes, igualacion)
        print("Se intersectan en: ", resultado)
    except Exception as e:
        print("Las ecuaciones no van a coincidir en ningún punto.")
        
# Primer sistema
print("Primer sistema")
solve([[3, 2] , [6, 4]], [6, -9])
print("--------------------")

# Segundo sistema
print("Segundo sistema")
solve([[1, 1] , [1, -4]], [3, 1])
print("--------------------")

# Tercer sistema
print("Tercer sistema")
solve([[2, -1, 2] , [2, 3, -1], [1, 2, 2]], [3, 0, -12])

Primer sistema
Las ecuaciones no van a coincidir en ningún punto.
--------------------
Segundo sistema
Se intersectan en:  [2.6 0.4]
--------------------
Tercer sistema
Se intersectan en:  [ 3.65217391 -3.7826087  -4.04347826]
